stages:
  data_ingestion:
    cmd: python src/violenceReporter/pipeline/stage_01_data_ingestion.py
    deps:
      - src/violenceReporter/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Dataset

  data_transformation:
    cmd: python src/violenceReporter/pipeline/stage_02_data_transformation.py
    deps:
      - src/violenceReporter/pipeline/stage_02_data_transformation.py
      - config/config.yaml
    params:
      - IMAGE_HEIGHT
      - IMAGE_WIDTH
      - SEQUENCE_LENGTH
    outs:
      - artifacts/data_transformation

  prepare_base_model:
    cmd: python src/violenceReporter/pipeline/stage_03_prepare_base_model.py
    deps:
      - src/violenceReporter/pipeline/stage_03_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_HEIGHT
      - IMAGE_WIDTH
      - SEQUENCE_LENGTH
      - INCLUDE_TOP
      - TRAINABLE
      - CLASSES
      - WEIGHTS
      - FREEZE_TILL
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/violenceReporter/pipeline/stage_04_model_training.py
    deps:
      - src/violenceReporter/pipeline/stage_04_model_training.py
      - config/config.yaml
      - artifacts/data_ingestion/Dataset
      - artifacts/prepare_base_model
    params:
      - IMAGE_HEIGHT
      - IMAGE_WIDTH
      - EPOCHS
      - BATCH_SIZE
      - TEST_SIZE
    outs:
      - artifacts/training

  evaluation:
    cmd: python src/violenceReporter/pipeline/stage_05_model_evaluation.py
    deps:
      - src/violenceReporter/pipeline/stage_05_model_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/Dataset
      - artifacts/training/model.h5
    params:
      - IMAGE_HEIGHT
      - IMAGE_WIDTH
      - SEQUENCE_LENGTH
      - INCLUDE_TOP
      - WEIGHTS
      - TRAINABLE
      - FREEZE_TILL
      - CLASSES
      - TEST_SIZE
      - EPOCHS
      - BATCH_SIZE
    outs:
      - artifacts/evaluation
    metrics:
      - scores.json:
          cache: false